INSERT INTO burgers VALUES(0, 'Golden Goat Burger', FALSE, CURRENT_TIMESTAMP);
INSERT INTO burgers VALUE(0, 'Brave Beef Burger', FALSE, CURRENT_TIMESTAMP);
INSERT INTO burgers VALUE(0, 'Charming Chicken Burger', FALSE, CURRENT_TIMESTAMP);

